name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      bump:
        description: "Bump version (patch, minor, major)"
        required: true

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Bundle with webpack
        run: npm run build:webpack

      - name: Bump version and create release
        if: github.event_name == 'workflow_dispatch'
        id: create_release
        run: |
          NEW_VERSION=0.1.0
          git push --follow-tags
          TAG_NAME="v$NEW_VERSION"
          echo "::set-output name=tag::$TAG_NAME"
          echo "::set-output name=release_name::Release $TAG_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        if: github.event_name == 'workflow_dispatch'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_release.outputs.tag }}
          release_name: ${{ steps.create_release.outputs.release_name }}

      - name: Publish to npm registry
        if: github.event_name == 'workflow_dispatch'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
